@EmployeesAPI_HostAddress = http://localhost:5276

GET {{EmployeesAPI_HostAddress}}/api/employees
Accept: application/json

###

GET {{EmployeesAPI_HostAddress}}/api/employees/1
Accept: application/json

###
