name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: ubuntu-latest
    environment: AzureDevOps
    env: # Set the secret as an input
      AZORG: ${{ secrets.AZORG }}
      AZUREPAT: ${{ secrets.AZUREPAT }}
      AZUSERNAME: ${{ secrets.AZUSERNAME }}
      AZUSER_EMAIL: ${{ secrets.AZUSER_EMAIL }}
      TEST: 'TESTTTTT'
      NAME: 'testsetsetestet'
    steps:
        - name: Print name
          shell: pwsh
          run: echo "Hello $NAME"
        - name: scripts
          shell: pwsh
          run: |
            git --version
            git config --global user.name $env:AZUSERNAME
            git config --global user.email $env:$AZUSER_EMAIL
            git config --list
            echo "===================================="
            echo "https://$(env:AZUSERNAME)AAAA$env:AZUREPAT@dev.azure.com/$env:AZORG/MirroredLearningAspire/_git/MirroredLearningAspire"
            git clone "https://$AZUSERNAME :$AZUREPAT@dev.azure.com/$AZORG/MirroredLearningAspire/_git/MirroredLearningAspire"
        
  
