name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: ubuntu-latest
    env: # Set the secret as an input
      AZURE_PAT: ${{ secrets.AZURE_PAT }}
      AZURE_ORG: ${{ secrets.AZORG }}
      AZURE_USER: ${{ secrets.AZURE_USER }}
      AZURE_EMAIL: ${{ secrets.AZURE_EMAIL }}
      TEST: 'TESTTTTT'
      NAME: 'testsetsetestet'
    steps:
        - name: Test Bash script
          env:
            NAME1: test1
          shell: bash
          run: |
            echo "Hello TEST: $TEST"
            echo "Hello NAME: $NAME"
            echo "Hello NAME1: $NAME1"
            #$name3 = 'testst name3'
            #echo "Hello nam3: $name3"
            
        - name: Test Powershell
          run: |
            Write-Host "Env:AZURE_ORG: $Env:AZURE_ORG"
          shell: pwsh
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0  
        - name: Mirroring
          shell: bash
          run: |
            echo "checkout to the branch should be mirrored"
            mirroredBranch="master"
            destinationRepo="MirroredLearningAspire"
            git checkout -B $mirroredBranch
            echo "mirrored branch: $mirroredBranch"
            echo "destination repository: $destinationRepo"
            echo "remove .git folder"
            rm -rf .git
            ls
            echo "clone destination repository"
            cd ..
            ls
            url="https://$AZURE_PAT@dev.azure.com/$AZURE_ORG/$destinationRepo/_git/$destinationRepo"
            git clone $url
            git checkout -B $mirroredBranch
            
            echo "copy new changes from source repo to destination repo"
            cd ..
            cp -rf ./LearningAspire "./$destinationRepo"

            echo "add the mirrored codes to the destination branch"
            cd "$destinationRepo" 
            git add .
            git commit -m "mirror repo on -$(date '+%Y-%m-%d-%H-%M-%S')"

            echo "push to remote origin"
            git push
  
        
