name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: ubuntu-latest
    env: # Set the secret as an input
      AZURE_PAT: ${{ secrets.AZURE_PAT }}
      AZURE_ORG: ${{ secrets.AZORG }}
      AZURE_USER: ${{ secrets.AZURE_USER }}
      AZURE_EMAIL: ${{ secrets.AZURE_EMAIL }}
      TEST: 'TESTTTTT'
      NAME: 'testsetsetestet'
    steps:
        - name: Test Bash script
          env:
            NAME1: test1
          shell: bash
          run: |
            echo "Hello TEST: $TEST"
            echo "Hello NAME: $NAME"
            echo "Hello NAME1: $NAME1"
            #$name3 = 'testst name3'
            #echo "Hello nam3: $name3"
            
        - name: Test Powershell
          run: |
            Write-Host "Env:AZURE_ORG: $Env:AZURE_ORG"
          shell: pwsh
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0  
        - name: Mirroring
          shell: bash
          run: |
            echo "checkout to the branch should be mirrored"
            mirroredBranch="master"
            git checkout -B $mirroredBranch
        
            echo "remove .git folder"
            rm -rf .git
            echo "init git again"
            git init
            git config --global user.email $AZURE_EMAIL
            git config --global user.name $AZURE_USER
            git config --global init.defaultBranch main
            echo "add remote origin to AzureDevOps repository"
            echo "===================================="
            url="https://$AZURE_PAT@dev.azure.com/$AZURE_ORG/MirroredLearningAspire/_git/MirroredLearningAspire"
            echo "url: $url"
            git remote add origin $url
            
            echo "create a local branch master"
            git checkout -B "$mirroredBranch"
        
            echo "add the mirrored codes to the local branch"
            git add .
            git commit -m "mirror repo on -$(date '+%Y-%m-%d-%H-%M-%S')"
        
            echo "push to remote origin"
            git push --set-upstream origin "$mirroredBranch"
        
