name: "Mirror repository to Azure DevOps"

on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup dotnet cli
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Install Aspire workload
        run: dotnet workload restore 
        
      - name: Build whole .net solution before mirroring
        run: dotnet build
        
      - name: Mirror development repository to the deployement repository on Azure DevOps
        run: |
          git remote add AzureDevOps https://trungdd2811:7ss2nmojnhjxwvycsmwoifcieoenj26umm3pvcuoe4c2wmnyy74a@dev.azure.com/trungdd2811/MirroredLearningAspire/_git/MirroredLearningAspire
          git push AzureDevOps
