name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: windows-latest
    environment: AzureDevOps
    steps:
        - name: scripts
          env: # Set the secret as an input
            AZORG: ${{ secrets.AZORG }}
            AZUREPAT: ${{ secrets.AZUREPAT }}
            AZUSERNAME: ${{ secrets.AZUSERNAME }}
            AZUSER_EMAIL: ${{ secrets.AZUSER_EMAIL }}
            TEST: TESTTTTT
          run: |
            git --version
            git config --global user.name $AZUSERNAME
            git config --global user.email $AZUSER_EMAIL
            git config --list
            echo env.TEST
            echo $env.TEST
            echo $TEST
            echo $env.AZORG
            echo "===================================="
            $url = "https://$AZUREPAT@dev.azure.com/$AZORG/$TEST/MirroredLearningAspire/_git/MirroredLearningAspire"
            echo $url
            dir
            #git clone $url
  
