name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: windows-latest
    env: # Set the secret as an input
      AZURE_PAT: ${{ secrets.AZURE_PAT }}
      AZURE_ORG: ${{ secrets.AZORG }}
      TEST: 'TESTTTTT'
      NAME: 'testsetsetestet'
    steps:
        - name: Test Bash script
          env:
            NAME1: test1
          shell: bash
          run: |
            echo "Hello TEST: $TEST"
            echo "Hello NAME: $NAME"
            echo "Hello NAME1: $NAME1"
            #$name3 = 'testst name3'
            #echo "Hello nam3: $name3"
            
        - name: Test Powershell
          run: |
            Write-Host "Env:AZURE_ORG: $Env:AZURE_ORG"
          shell: pwsh
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0  
        - name: Mirroring
          shell: pwsh
          run: |
            dir
            cd ..
            dir
            #$pat = ${Env:AZURE_PAT}
            #$org = ${Env:AZURE_ORG}
            #git --version
            #git config --list
            echo "===================================="
            #$url = "https://$pat@dev.azure.com/$org/MirroredLearningAspire/_git/MirroredLearningAspire"
            #Write-Host "url: $url"
            #git clone https://tw4sw3fnjfbhtrjs32rh76dpowr5i5jxhecxbfetv2brvj2dgs6q@dev.azure.com/trungdd2811/MirroredLearningAspire/_git/MirroredLearningAspire
            #git push --mirror $url
        
