name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: windows-latest
    environment: AzureDevOps
    steps:
        - name: scripts
          run: |
            git --version
            dir
            #git clone https://trungdd2811@dev.azure.com/trungdd2811/MirroredLearningAspire/_git/MirroredLearningAspire
