name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: windows-latest
    environment: AzureDevOps
    env: # Set the secret as an input
      AZORG: ${{ secrets.AZORG }}
      AZUREPAT: ${{ secrets.AZUREPAT }}
      AZUSERNAME: ${{ secrets.AZUSERNAME }}
      AZUSER_EMAIL: ${{ secrets.AZUSER_EMAIL }}
      TEST: 'TESTTTTT'
      NAME: 'testsetsetestet'
    steps:
        - name: Print name
          env:
            NAME1: test1
          shell: bash
          run: |
            echo "Hello TEST: $TEST"
            echo "Hello NAME: $NAME"
            echo "Hello NAME1: $NAME1"
            #$name3 = 'testst name3'
            #echo "Hello nam3: $name3"
            
        - name: Test powershell
          run: |
            Write-Host "Env:AZORG $Env:AZORG"
          shell: pwsh
          
        - name: scripts
          shell: pwsh
          run: |
            $username = ${Env:AZUSERNAME}
            $email = ${Env:$AZUSER_EMAIL}
            $pat = ${Env:$AZUREPAT}
            $org = ${Env:$AZORG}
            git --version
            git config --global user.name $username
            git config --global user.email $email
            git config --list
            echo "===================================="
            #echo "https://$(env:AZUSERNAME)AAAA$env:AZUREPAT@dev.azure.com/$env:AZORG/MirroredLearningAspire/_git/MirroredLearningAspire"
            #git clone "https://$AZUSERNAME :$AZUREPAT@dev.azure.com/$AZORG/MirroredLearningAspire/_git/MirroredLearningAspire"
        
  
