name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: windows-latest
    environment: AzureDevOps
    steps:
        - name: scripts
          env: # Set the secret as an input
            AZUSERNAME: ${{ secrets.AZUSERNAME }}
          run: |
            git --version
            git config --global user.name "trungdd2811"
            git config --global user.email "trungdd2811@gmail.com"
            git config --list
            echo AZUSERNAME
            dir
            #git clone https://trungdd2811:hpjyih4t7ohamonqyl7xtr7ztf5huqxf2bwavmbikqtnsqelkara@dev.azure.com/trungdd2811/MirroredLearningAspire/_git/MirroredLearningAspire
            dir
  
