name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: ubuntu-latest
    environment: AzureDevOps
    steps:
        - name: scripts
          env: # Set the secret as an input
            AZORG: ${{ secrets.AZORG }}
            AZUREPAT: ${{ secrets.AZUREPAT }}
            AZUSERNAME: ${{ secrets.AZUSERNAME }}
            AZUSER_EMAIL: ${{ secrets.AZUSER_EMAIL }}
            TEST: 'TESTTTTT'
            NAME: 'testsetsetestet'
          run: |
            git --version
            #git config --global user.name $AZUSERNAME
            #git config --global user.email $AZUSER_EMAIL
            echo $TEST
            echo "===================================="
            $url = "$AZUREPAT@dev.azure.com/$AZORG/$TEST/MirroredLearningAspire/_git/MirroredLearningAspire"
            echo $url
            #git clone $url
        - name: Print name
          run: echo "Hello $NAME"
  
