name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: windows-latest
    environment: AzureDevOps
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: scripts
          run: |
            git --version
            dir
            cd ..
            dir 
            git clone https://yniyxfx6ij4lr7nlz7pgo3o2ricchxx6rkr6mflzzozldlpym5ra@dev.azure.com/trungdd2811/MirroredLearningAspire/_git/MirroredLearningAspire
