name: "Mirror repository to Azure DevOps"
on:
  push:
    branches:
      - master

jobs:
  mirror:
    name: Mirror repository to Azure DevOps
    runs-on: ubuntu-latest
    environment: AzureDevOps
    env: # Set the secret as an input
      AZORG: ${{ secrets.AZORG }}
      AZUREPAT: ${{ secrets.AZUREPAT }}
      AZUSERNAME: ${{ secrets.AZUSERNAME }}
      AZUSER_EMAIL: ${{ secrets.AZUSER_EMAIL }}
      TEST: 'TESTTTTT'
      NAME: 'testsetsetestet'
    steps:
        - name: scripts
          run: |
            git --version
            git config --global user.name $AZUSERNAME
            git config --global user.email $AZUSER_EMAIL
            echo "===================================="
            echo "https://$AZUREPAT@dev.azure.com/$AZORG/MirroredLearningAspire/_git/MirroredLearningAspire"
            #git clone $url
        - name: Print name
          run: echo "Hello $NAME"
  
